name: redis on tag

on:
  push:
    branches: 
      - 'test-workflow'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
      - '[0-9]+.[0-9]+.[0-9]+*'
      - 'v[0-9]+.[0-9]+.[0-9]+-(CR|Beta|milestone)[0-9]*'
      - '[0-9]+.[0-9]+.[0-9]+-(CR|Beta|milestone)[0-9]*'

permissions:
  id-token: write
  contents: read

jobs:
  calling-reusable-workflow:
    uses: inqwise/ansible-automation-toolkit/.github/workflows/goldenimage-workflow.yml@default
    with:
      APP: "redis"
      PROJECT: "pension-"